### ISSUE TITLE
Incompatibility With an E-102 texture replacement mod

### ISSUE THREAD

**Issue by falsemcfakeman2** [PiKeyAr/sadx_dreamcast#220] opened 2020-01-02 02:48 UTC
Version=0.5272

The Playable E-Series Mod, which replaces E102.PVM with another texture, doesn't work with this mod. Mod load order doesn't matter.

I'm not sure why that would be the case, or if there's a way of using a toggle in config to make it work. Would it be possible to make it work, or to add more toggles to allow it to work?

**Comment by PiKeyAr** [comment] 2020-01-07 02:02
Does it work if you make a duplicate of each PVM archive and add a _DC suffix to its name?
E.g. E102.PVM -> E102_DC.PVM

**Comment by PiKeyAr** [comment] 2020-01-31 10:16
Please reopen if it doesn't help, closing this for now.

**Closed by PiKeyAr** 2020-01-31 10:16 UTC

**Comment by falsemcfakeman2** [comment] 2020-02-04 05:20
Sorry, life got in the way. Tested the textures with the _DC added and it works fine!

Thanks much!
