### ISSUE TITLE
Beta Release Bug Report

### ISSUE THREAD

**Issue by TheWonderFromDownUnder** [PiKeyAr/sadx_dreamcast#212] opened 2019-08-10 22:06 UTC
I have tried the new beta release of the DC Conversion revamp. While it is a substantial improvement and an impressive piece of work (Casinopolis in particular looks stunning), there are indeed some bugs I've noticed that I'd like to see ironed out for the final release;

- The dolphins in Emerald Coast still don't reset properly upon restart. (as shown here: https://twitter.com/SA1Facts/status/1152276380685656064)

- The doors on the Twinkle Park entrance in Station Square are misplaced.

- Something's not right with the Light Speed ring path in SS Sewers. With the LS Dash distance hack on, it's unusually difficult to get out of the sewers, as the game struggles to launch Sonic high enough to get out of the well.

- On a similar note, the ring path that leads to the jump panel in Icecap 1 also acts strangely, launching Sonic much higher than necessary. Happens regardless of LS Dash Distance hack being turned on or off.

- The game seems to not load lighting immediately for Chaos 0, but only in the Boss Attack mode.

- Going into a stage in Trial Mode, then exiting to the Character Select, and then again to the Main Menu makes the game take an unusually long amount of time to load the latter.

**Comment by TheWonderFromDownUnder** [comment] 2019-08-11 18:48
Extra note about EC Dolphins: While the bug seems largely resolved, this particular set of dolphins (seen below, before the ramp near the goal) work inconsistently from the others, only appearing after a restart.

![Screenshot (2734)](https://user-images.githubusercontent.com/52037295/62838206-e7090d80-bc70-11e9-8d68-236350f06c9a.png)

**Comment by TheWonderFromDownUnder** [comment] 2019-08-11 19:59
A couple extra bugs:

- The MR Base tunnel seems to be rendered over Sonic's Spin Dash and LS Aura effects. (Examples below)

![Screenshot (2744)](https://user-images.githubusercontent.com/52037295/62838796-bd53e480-bc78-11e9-9615-9b9265944e34.png)

![Screenshot (2745)](https://user-images.githubusercontent.com/52037295/62838805-d197e180-bc78-11e9-8b0a-4fbd57f67a24.png)

- When hitting one of the door switches in Lost World 1, the camera can infrequently get caught on the door instead of returning to the player's position. Cause unknown.

**Comment by TheWonderFromDownUnder** [comment] 2019-08-11 22:53
Extra note about MR Base Tunnel Bug: The same issue also occurs in the SS Twinkle Park Entrance (As shown below).

![Screenshot (2746)](https://user-images.githubusercontent.com/52037295/62840452-dec1ca00-bc92-11e9-9572-4ff7aff63294.png)

**Comment by sa-nd** [comment] 2019-08-11 23:31
Something like the MR base tunnel bug also happens in speed highway, during at dawn, the same type of visual bug happens to all the windows as well as the fountain. This bug also overlaps super sonics 'shield'.  

Super Sonic  breaks emerald coast in a different way now, before he could float on the water and bypass the entire stage and head straight to the goal. Now he can't float on the water and will fall to his death if he falls in deep water(Which is fine, it's the other parts that suck). If he falls in shallow water he'll get stuck underneath the water, you can only escape if you turn back into regular sonic. The worst part about this is, if you walk/float into the shallows without jumping into it you will fall through the ground and die.

Also, after the most recent update, the sound effect that plays when the cops run up to chaos 0 and point their guns at him no longer plays.(Pretty minor, but worth mentioning.)

**Comment by TheWonderFromDownUnder** [comment] 2019-08-12 10:17
- The second group of Icicles in Icecap 2 (shown below) are strangely unresponsive.

![Screenshot (2756)](https://user-images.githubusercontent.com/52037295/62858313-df3d7d80-bcf1-11e9-8d57-c1cce86de0a9.png)

- Somehow, after extended play, the ocean model for Emerald Coast refused to load (As shown below). Exiting and re-entering the level does not correct it at this point. Cause unknown.

![Screenshot (2753)](https://user-images.githubusercontent.com/52037295/62857950-ddbf8580-bcf0-11e9-9f79-a579671382fc.png)

- When backing out from the main menu to the title screen, the latter takes a longer amount of time to load than expected.

- Occasionally, the game will load but refuse to play sound effects (expect for music and voices) unless you click out of the game tab and click in again.

**Comment by TheWonderFromDownUnder** [comment] 2019-08-12 12:17
- When going on the platform that takes you to the EC Interior, the hole below it will sometimes not open as it should, leaving player standing awkwardly until the Interior loads.

![Screenshot (2757)](https://user-images.githubusercontent.com/52037295/62864039-8cb88d00-bd02-11e9-9525-57de3ed29cfb.png)

**Comment by TheWonderFromDownUnder** [comment] 2019-08-12 13:52
- Sometimes, the car models in Speed Highway 3 don't load. Cause unknown.

![Screenshot (2760)](https://user-images.githubusercontent.com/52037295/62869948-b4aeed00-bd10-11e9-8170-7dca045100d4.png)

**Comment by PiKeyAr** [comment] 2019-08-12 15:35
Hi, and thanks a lot for the reports.
@TheWonderFromDownUnder I can't seem to reproduce the issues with Emerald Coast ocean and Speed Highway cars, could you share your SADXModLoader.ini and the steps to reproduce it consistently?

**Comment by TheWonderFromDownUnder** [comment] 2019-08-12 18:50
This is what my SADXModLoader.ini has been set to since I started testing.

![Screenshot (2765)](https://user-images.githubusercontent.com/52037295/62889636-ab864600-bd39-11e9-8a76-c5dfeb4a0422.png)

And my DC Conversion config.ini.

![Screenshot (2767)](https://user-images.githubusercontent.com/52037295/62889665-be007f80-bd39-11e9-9f76-887de7701ae7.png)

As for recreating the bugs, I've yet to figure them out, but will post it here if I do.

**Comment by PiKeyAr** [comment] 2019-08-12 20:14
@TheWonderFromDownUnder While I still don't know what could be causing it, I've made some changes that can potentially resolve it. Please try with the latest update.

**Comment by PiKeyAr** [comment] 2019-08-12 21:47
@TheWonderFromDownUnder I believe I've found the original issue behind disappearing ocean and cars, please test with the latest update.

**Comment by PiKeyAr** [comment] 2019-08-12 22:19
Looks like the fix breaks other levels. I'll investigate further.

**Comment by TheWonderFromDownUnder** [comment] 2019-08-12 22:22
The issue seems to be resolved, but the effects for the Item Boxes and Dolphins are glitched as of the update.


![Screenshot (2783)](https://user-images.githubusercontent.com/52037295/62902606-0890f480-bd58-11e9-95f1-9abc3825c210.png)

![Screenshot (2782)](https://user-images.githubusercontent.com/52037295/62902617-10e92f80-bd58-11e9-9eca-2adb27954b61.png)


Only effects Emerald Coast 2, to my knowledge. The other levels, including Speed Highway 3, work fine in this regard.

**Comment by PiKeyAr** [comment] 2019-08-12 22:23
No, it's broken. I'm reverting it to investigate further.

**Comment by TheWonderFromDownUnder** [comment] 2019-08-12 22:26
Oh right. My mistake.

**Comment by TheWonderFromDownUnder** [comment] 2019-08-12 22:32
Something I did mean to mention is that the spin dash rendering bugs, though partially resolved in the update, are still not showing properly on the spin charge.

![Screenshot (2775)](https://user-images.githubusercontent.com/52037295/62902914-f95e7680-bd58-11e9-9b1b-cb5106dbb696.png)

**Comment by PiKeyAr** [comment] 2019-08-12 23:43
@TheWonderFromDownUnder I believe I've finally fixed the textures issue, it's in the last update.
As for Station Square glass issues, there won't be any more fixes beyond what's currently done.

**Comment by sa-nd** [comment] 2019-08-14 05:17
I've found some more issues and oddities;

- Knuckles shadow is rendered above the digging animation
![20190813152137_1](https://user-images.githubusercontent.com/52898048/62995534-d6de6300-be15-11e9-99cd-3761888831ce.png)

Old Dreamcast mod
![20190813215202_1](https://user-images.githubusercontent.com/52898048/62995547-e8c00600-be15-11e9-9e0f-896610732e31.png)

- The water in the secret cave in Bigs version of emerald coast looks... Weird.
![20190813155356_1](https://user-images.githubusercontent.com/52898048/62995614-2c1a7480-be16-11e9-896d-e323e3407d89.png)
![20190813155351_1](https://user-images.githubusercontent.com/52898048/62995615-2c1a7480-be16-11e9-9cb7-048e16e0065f.png)

Old Dreamcast mod
![20190813212936_1](https://user-images.githubusercontent.com/52898048/62995629-3dfc1780-be16-11e9-9873-6bddfc5ab98b.png)

- There's an enemy missing in sky deck act 3, though I'm not sure if he was removed intentionally or not
![20190813142505_1](https://user-images.githubusercontent.com/52898048/62995690-89162a80-be16-11e9-90ee-21074b766d7e.png)

Old Dreamcast mod
![20190813210549_1](https://user-images.githubusercontent.com/52898048/62995699-93382900-be16-11e9-8aa7-97cd8472ddce.jpg)

- The underwater tunnel entrance in bigs version of ice cap has some weird properties now, textures seem to become transparent when viewed at certain angles.
![20190813154908_1](https://user-images.githubusercontent.com/52898048/62995815-24a79b00-be17-11e9-9084-038005c06e03.png)
![20190813154926_1](https://user-images.githubusercontent.com/52898048/62995905-75b78f00-be17-
![20190813154935_1](https://user-images.githubusercontent.com/52898048/62995906-78b27f80-be17-11e9-841d-60316fce43e0.png)
11e9-
![20190813155000_1](https://user-images.githubusercontent.com/52898048/62995918-8405ab00-be17-11e9-8ea6-2e2794c1ced5.png)
8249-d5becbb6b22a.png)
![20190813154950_1](https://user-images.githubusercontent.com/52898048/62995925-88ca5f00-be17-11e9-8b43-ec35f55f3254.png)

- In Sky deck act 1, the bottom of the four pillars around the cannon appear sooner than they should
![20190813142142_1](https://user-images.githubusercontent.com/52898048/62996030-03937a00-be18-11e9-8446-fd709d99333c.png)

Old Dreamcast mod
![20190813210133_1](https://user-images.githubusercontent.com/52898048/62996042-0ee6a580-be18-11e9-86ec-0925f20276f2.png)

**Comment by TheWonderFromDownUnder** [comment] 2019-08-14 13:59
- The SA Japanese setting in the SET layouts and cameras section still uses the International cameras in Station Square.

**Comment by sa-nd** [comment] 2019-08-14 21:28
Here are a few visual bugs I found:
The first two are very similar to a previously mentioned bug regarding the foliage in emerald coast when viewed from underwater, only in twinkle park and hot shelter.
 
![20190813160021_1](https://user-images.githubusercontent.com/52898048/63056697-6ed35f80-be9d-11e9-9f92-0d0c1af0af2a.png)
![Inked20190813154525_1_LI](https://user-images.githubusercontent.com/52898048/63057183-83fcbe00-be9e-11e9-9a78-820fd371883b.png)

The third is a visual error when gamma dies. I'm aware in the dreamcast version, some lights on gamma disappear when he dies.  I'm also aware that is in itself a bug that was in the original game, but did part of gamma's right foot disappear sometimes too?  
![20190813160648_1](https://user-images.githubusercontent.com/52898048/63057691-a80ccf00-be9f-11e9-9fce-e2610aab9f14.png)

**Comment by sa-nd** [comment] 2019-08-14 23:01
Sky Deck is a bit more unstable in the beta, I mean when the level loads, it's fine, but it has a bit of  trouble loading now, sometimes it loads pretty fast, (Normal) while other time's it take's an extra 10 seconds or so and when that happens, it's a 50/50 chance whether it loads or crashes. 
I have no idea why.

**Comment by sa-nd** [comment] 2019-08-15 00:19
Gamma has a shadow now on the Character Select screen
![20190814171528_1](https://user-images.githubusercontent.com/52898048/63064729-933c3580-beb7-11e9-89cf-f0b0cc7ccd3a.png)

**Comment by sa-nd** [comment] 2019-08-15 00:54
That Gamma shadow was just the tip of the iceberg!
I've seen dozens of more shadow errors all over the game now!

- Several objects, especially rings, have floating shadows under them now.
![20190814172926_1](https://user-images.githubusercontent.com/52898048/63065536-48bcb800-bebb-11e9-8176-c4975cf58e67.png)
![20190814172529_1](https://user-images.githubusercontent.com/52898048/63065537-48bcb800-bebb-11e9-83e4-0f62cdfa7e90.png)
![20190814172751_1](https://user-images.githubusercontent.com/52898048/63065538-49554e80-bebb-11e9-8089-dc9734eb33e9.png)
![20190814172911_1](https://user-images.githubusercontent.com/52898048/63065540-49554e80-bebb-11e9-9369-4ed4cdc18c64.png)
![20190814173055_1](https://user-images.githubusercontent.com/52898048/63065551-540fe380-bebb-11e9-8fa1-73cdcab35c55.png)
![20190814173401_1](https://user-images.githubusercontent.com/52898048/63065562-5d00b500-bebb-11e9-813e-c1bfac2421ee.png)
![20190814173229_1](https://user-images.githubusercontent.com/52898048/63065561-5a05c480-bebb-11e9-8136-46e7f30b212b.png)
![20190814173634_1](https://user-images.githubusercontent.com/52898048/63065568-62f69600-bebb-11e9-94d7-e6c6d2e82ca5.png)

- Shadows lack transparency now and it's very noticeable when using the spindash.
![20190814173240_1](https://user-images.githubusercontent.com/52898048/63065620-9c2f0600-bebb-11e9-9424-2a1ea61d174d.png)

A couple other observations; 

- The blue trail sonic leaves behind when jump dashing or spin dashing, doesn't quite look right in the windy valley tornado.
![20190814173138_1](https://user-images.githubusercontent.com/52898048/63065773-368f4980-bebc-11e9-9937-bc36928d747c.png)

- There isn't any wind down near the kill plane in red mountain while playing as knuckles.
![20190814172348_1](https://user-images.githubusercontent.com/52898048/63065837-6e968c80-bebc-11e9-90aa-d479b533f3c4.png)

**Comment by sa-nd** [comment] 2019-08-15 01:51
E101MK2 is broken now.
![20190814182416_1](https://user-images.githubusercontent.com/52898048/63066968-9b00d780-bec1-11e9-8e84-bfd69753690a.png)

The fight starts off normal, until beta loses half of his health and teleports above the arena to fire energy blasts at you. The problem is, he teleports dozens of miles into the air...
The camera tries to catch up following beta into the sky...
![20190814182431_1](https://user-images.githubusercontent.com/52898048/63067130-545fad00-bec2-11e9-8a22-3a5b0b5d26cd.png)

You get a nice view of the Egg Carrier for a few seconds, then you can see one of beta's energy blasts hurtling towards you... (It never reach's you though.)

![20190814182437_1](https://user-images.githubusercontent.com/52898048/63067251-dbad2080-bec2-11e9-9322-ad83a499ee87.png)

Then the camera does a 180 and points towards the sun for a few seconds...

![20190814182443_1](https://user-images.githubusercontent.com/52898048/63067285-0e571900-bec3-11e9-80d2-aa26f5ae57df.png)

Then the camera returns to gamma, but beta never returns to the arena.

![20190814182645_1](https://user-images.githubusercontent.com/52898048/63067334-55dda500-bec3-11e9-8d44-bc4eb493ab03.png)

You can wander around all you like, collect all the rings but beta never comes back, he does continue firing at you however, and every time he does, the camera flies into the sky again.
Unfortunately the fight is currently unbeatable, as all you can do is let the timer run out at that point.

![20190814182705_1](https://user-images.githubusercontent.com/52898048/63067466-f7fd8d00-bec3-11e9-9b53-888ad80de37d.png)

**Comment by PiKeyAr** [comment] 2019-08-15 01:55
The shadows thing and most of the gameplay issues mentioned above were caused by an experimental fix that I reverted. They shouldn't happen anymore.

**Comment by sa-nd** [comment] 2019-08-15 02:38
I would like to note that while the latest changelog said, "Fixed Gamma material bugs that show up when he is hit with no rings" He's still losing a foot when he dies.
![20190814192745_1](https://user-images.githubusercontent.com/52898048/63069217-ef5c8500-beca-11e9-9500-90ea3ff67c1d.png)

**Comment by sa-nd** [comment] 2019-08-15 03:27
Egg Hornet has a tendency to crash with as any of the 3 characters for some reason.

**Comment by PiKeyAr** [comment] 2019-08-15 03:41
I haven't been able to reproduce either of the crashes reported here so far. Are there any specific steps to reproduce them? DC Conversion config/mod setup perhaps?

**Comment by PiKeyAr** [comment] 2019-08-15 04:05
@sa-nd If you have any files in the folder `%LocalAppData%\CrashDumps` (you can paste this highlighted bit into Explorer address bar or the "Run" command), please share because those can help investigate the crashes.

**Comment by sa-nd** [comment] 2019-08-15 04:48
Whatever was wrong with sky deck seems to have already been fixed, as I haven't had a problem with it for a while. One of the updates not too long after I reported it seemed to fix it. It use to get stuck on the loading screen (Sky Deck Title Card) for a long amount of time, whether the stage actually started or not after that was 50/50. After one of the updates it stopped happening, it loads as fast as any other stage now.
 
For Egg Hornet, I've had it crash at least once for all 3 characters who fight this boss. When it does crash, it does so when first starting the boss battle. (During the black screen, while the game is loading)  Even then, it was pretty random when it occurred, it happened once, not too long after starting the game, and another time when I had already been playing for a few hours. 
I've replayed the boss quite a few times and I would say it crash, 1 out 3 times.

I'll upload those files shortly.

**Comment by sa-nd** [comment] 2019-08-15 05:08
Here you go.
http://www.mediafire.com/folder/0489sr4r9cjs1/Crash_files

**Comment by sa-nd** [comment] 2019-08-15 05:12
Here you go, all 3 files.
http://www.mediafire.com/file/t9xgfc4g21b7etk/sonic.exe.12168.dmp/file
http://www.mediafire.com/file/r0fn1gp0b63qw0k/sonic.exe.12276.dmp/file
http://www.mediafire.com/file/6xwmeb9xtmaobom/sonic.exe.5748.dmp/file

**Comment by PiKeyAr** [comment] 2019-08-15 07:06
Thanks for sharing the files. Looks like it crashed trying to render a model. I've just made some adjustments to how it renders the ocean model, so maybe it won't crash anymore.

**Comment by TheWonderFromDownUnder** [comment] 2019-08-15 16:29
- As of the current version, attempting to use a Chao Garden teleporter will crash the game.

**Comment by TheWonderFromDownUnder** [comment] 2019-08-15 17:20
- Part of the conveyors in Speed Highway cause the player's shadow to fall through it. It's like this in the Dreamcast version too, but it's still strange and inconsistent with other platforms in the game.

![Screenshot (2796)](https://user-images.githubusercontent.com/52037295/63112684-bedb2080-bf88-11e9-963a-bfce05c1fec0.png)

**Comment by sa-nd** [comment] 2019-08-15 23:20
When I created a new file and checked the character select screen, none of the other character names were grayed out like they're supposed to be before you unlock them. They're not actually unlocked though.
![20190814204855_1](https://user-images.githubusercontent.com/52898048/63133123-8df2ef80-bf78-11e9-9666-633c0654c26a.png)

**Comment by PiKeyAr** [comment] 2019-08-16 03:28
Haven't been able to reproduce this. Make sure the "All characters unlocked in Adventure Mode" code is disabled in the Mod Manager. Also Sonic is unlocked by default.

**Comment by sa-nd** [comment] 2019-08-16 04:27
The "All characters unlocked in Adventure Mode" code was off.  I was showing sonic so you could see the 0% at the bottom right to prove that it was a new file. (Since sonic is the only character available at the start normally, his percentage being at zero shows that I haven't done anything yet on this file.)  
I disabled all mods except for dreamcast conversion as well as disabling all codes I had on. The 
problem still occurred.
![20190815204513_1](https://user-images.githubusercontent.com/52898048/63143233-23ef4000-bfa2-11e9-8139-c1322d549482.png)
![20190815204519_1](https://user-images.githubusercontent.com/52898048/63142811-2ea8d580-bfa0-11e9-8d03-da069e1c262d.png)

It's not the Character name on the bottom that's bugged, but rather the names on the character select wheel. Here's how it appeared after I disabled the dreamcast conversion. 

![20190815210914_1](https://user-images.githubusercontent.com/52898048/63143028-39179f00-bfa1-11e9-8818-dbd62e3aaf72.png)
![20190815210918_1](https://user-images.githubusercontent.com/52898048/63143032-3b79f900-bfa1-11e9-88a8-b6f6f79d797b.png)

Then I turned on all the other mods and codes that I had on when I initially reported this, except for dreamcast conversion. This was the result.
![20190815205619_1](https://user-images.githubusercontent.com/52898048/63143157-d83c9680-bfa1-11e9-8f03-212b895595fd.png)
![20190815205625_1](https://user-images.githubusercontent.com/52898048/63143163-dc68b400-bfa1-11e9-8c38-d35083aaac2c.png)

Hope this helps.

**Comment by sa-nd** [comment] 2019-08-16 04:45
I didn't mean sonic was locked in my earlier post, just that the other characters, while their names were colored in like they were unlocked, they were still locked. (As they're supposed to be at the very start of the game.)

Sorry if I wasn't clear enough at first.

**Comment by PiKeyAr** [comment] 2019-08-16 04:59
Ah ok, I thought it was about the names at the bottom. It should be fixed now.

**Comment by sa-nd** [comment] 2019-08-16 05:02
Just checked and yes, it's fixed now,

**Comment by sa-nd** [comment] 2019-08-16 23:06
A couple of visual errors in windy valley act 1.
Noticeable just as this bridge falls apart, right before you get sucked into the tornado.
![20190816155702_1](https://user-images.githubusercontent.com/52898048/63202629-76326e80-c03f-11e9-8b4c-b5f430cd6327.png)

**Comment by sa-nd** [comment] 2019-08-17 04:48
Another similar issue inside the tornado, though only noticeable in the half second the camera moves outside the tornado as sonic hit's this spring.
![20190816212039_1](https://user-images.githubusercontent.com/52898048/63206746-0d62ea80-c06f-11e9-8f95-f5c4616b98d5.png)

Also, the street lanterns in station square don't light up properly, it looks like the light is rendering behind the lantern, making it look a little odd.


![20190816213019_1](https://user-images.githubusercontent.com/52898048/63206768-72b6db80-c06f-11e9-9637-8e87108f6f1c.png)
![20190816213410_1](https://user-images.githubusercontent.com/52898048/63206769-75b1cc00-c06f-11e9-847a-1f13b49ab5c1.png)
![20190816213455_1](https://user-images.githubusercontent.com/52898048/63206770-777b8f80-c06f-11e9-9189-806dc710e91a.png)

**Comment by TheWonderFromDownUnder** [comment] 2019-08-17 12:04
- This item box in Dilapidated Way should be moved down a bit, as the LS Dash trail lined up for it consistently fails to hit it.

![Screenshot (2816)](https://user-images.githubusercontent.com/52037295/63211463-4773d100-c0ef-11e9-84d4-c0ba5cc6e9ec.png)

**Comment by sa-nd** [comment] 2019-08-17 21:29
I noticed during the cutscene where sonic follows amy into twinkle park that there's a visual bug regarding the decoration above the main entrance when viewed at this angle.
![20190817141732_1](https://user-images.githubusercontent.com/52898048/63217432-5e202500-c0fb-11e9-896b-9c0a88ed3283.png)

**Comment by TheWonderFromDownUnder** [comment] 2019-08-17 21:36
-Ditto my previous point for this item box at the end of the section, except it should be moved up a bit.

![Screenshot (2820)](https://user-images.githubusercontent.com/52037295/63217512-51bdbb80-c13f-11e9-801c-c3b7b481b959.png)

**Comment by sa-nd** [comment] 2019-08-17 22:17
An earlier bug with sonic's shadow overlapping his spin dash is happening again in final egg, I noticed it in act 3.
![20190817150231_1](https://user-images.githubusercontent.com/52898048/63217815-d25dc700-c101-11e9-97cf-f151cc7f6601.png)

Also, the fog in the egg viper stage is overlapping the explosion at the end of the fight.
![20190817150911_1](https://user-images.githubusercontent.com/52898048/63217828-03d69280-c102-11e9-8075-295eac8abf35.png)

**Comment by sa-nd** [comment] 2019-08-17 23:15
Gamma doesn't explode at the end of his story.

**Comment by sa-nd** [comment] 2019-08-18 05:35
The trees in the mystic ruins jungle aren't affected by the fog at night.

![20190817221402_1](https://user-images.githubusercontent.com/52898048/63220518-5d5cb280-c13e-11e9-9ed3-5f31ed66e176.png)
![20190817221419_1](https://user-images.githubusercontent.com/52898048/63220519-5d5cb280-c13e-11e9-8538-d8e24a903d98.png)

Occasionally when you hit chaos 2, he doesn't transform into a ball but rather returns to his normal form. I mean, when chaos 2 is hurt, he melts into a puddle and then turns into a ball, when this glitch occurs, he melts into a puddle but then suddenly switchs back to normal, (With no animation, from puddle to normal form.) Not the worst thing ever, but it does look odd.

**Comment by PiKeyAr** [comment] 2019-08-18 06:13
The Chaos 2 issue sounds like a vanilla bug since I don't alter Chaos' behavior or animations. The trees do in fact get affected by fog, however they also ignore lighting (which is intentional) so that makes them pop a bit more.

**Comment by PiKeyAr** [comment] 2019-08-18 06:15
Thank you for taking part in the beta test. From now on, please report transparency-related issues [here](https://github.com/PiKeyAr/sadx_dreamcast/issues/42), and general mod issues on the general issues page.

**Closed by PiKeyAr** 2019-08-18 06:15 UTC
