### ISSUE TITLE
7th List of problems

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#71] opened 2017-03-07 19:38 UTC
Just a few things.

1. In Lost World Act 2, the lighting on Sonic (and Tails) is completely disabled, but on the Dreamcast it stays.

2. There's a stump next to Big's house that has absolutely no collision. A simple addition of a collision cylinder could fix it.
![imaginary stump](https://cloud.githubusercontent.com/assets/26051785/23676684/17a3f110-0343-11e7-8eb9-9d6a06f929ba.png)

3. There's one small tree on the floating island in the Angel Island area of Mystic Ruins that has no collision, either. It's on the right hand side when crossing the bridge to the floating island.
...Maybe there's a way to make it so that all of the trees cannot be clipped through? *nudge nudge*
![imaginary tree](https://cloud.githubusercontent.com/assets/26051785/23676692/215d97a6-0343-11e7-8ae0-8940bd643bde.png)

4. If Lost World is accessed through Trial Mode, and you pause and quit while in the dark room, the characters on the character select screen will have z-fighting between proper lighting and the "no lighting".
![feeling dark](https://cloud.githubusercontent.com/assets/26051785/23676707/2de3eba6-0343-11e7-82f7-6b4d827ab095.png)

5. Regarding the experimental code to disable the ocean in Big's secret fishing spot, if you swim too close the area from the outside, the ocean will still disappear. Perhaps this could resolved by checking for the player's Y position?
![swimming in air](https://cloud.githubusercontent.com/assets/26051785/23676726/3ddcdc16-0343-11e7-81c7-f59828898556.png)
Additionally, it appears that if you pause and exit while that code is active, when you enter the level again, the ocean will still be gone until you move back over to the loading area.

6. Don't know how fixable this is, but Tails will use his drowning animation (ironically enough) if he touches an air bubble underwater in the pond while he's following you in Emerald Coast Act 2.
![allergic to air](https://cloud.githubusercontent.com/assets/26051785/23676733/42e003c8-0343-11e7-90a4-9cb4c211c6c3.png)
This can be more easily seen and tested either by using the character select mod or the SADX trainer to hack Tails in Big's Emerald Coast and touch an air bubble there.

7. The glass on the lighthouse in Emerald Coast does not display palm tree leaves and moss through it. Also, the lighthouse in Big's Emerald Coast does not show objects at all through its glass, as well as small parts of the landtable.

8. At the origin of the level in Final Egg Act 2, there's that piece of level geometry. Does it need to be there, or can it be deleted?

9. In the Final Egg room of Mystic Ruins, there's some glass you can look through, and it shows the other side of the room.
![seeing through walls](https://cloud.githubusercontent.com/assets/26051785/23686957/faceb4a6-0371-11e7-9f81-40ec2eea16c9.png)
Problem is, is that the other side of the wall here isn't glass. You shouldn't be able to see through it to the other side of the room. ...It's a layering problem.
![seeing through walls 2](https://cloud.githubusercontent.com/assets/26051785/23686979/0f712b28-0372-11e7-8243-1dbe076b488f.png)

Have a great day. Still liking all the additions to these mods.

**Comment by PiKeyAr** [comment] 2017-03-08 08:49
Hi! Thanks for the report.

1 and 4 are not caused by this mod. As far as I know, 4 is a bug in SADX that happens without any mods.

2 and 3 - With regard to collision issues (and some other issues with the main games in general), I'm not particularly looking to recreate a "fixed" version of SA1 with this mod, so I generally don't look into collision issues unless they break the gameplay in a noticeable way and are caused specifically by my mods. However, if you have fixed it in your SET files, I'll be glad to integrate your fixes, as long as they are based on SA1 SET files.

5 - fixed

6 - this is also outside the scope of what this mod does, maybe SADXFE

7 - requires order-independent transparency

8 - what piece of level geometry?

9 - fixed

**Comment by supercoolsonic** [comment] 2017-03-08 15:25
Re: 2 and 3: Yes, they're fixed in the layout files I posted in my first report here. If it's already done, I don't see any harm in making the game appear more polished. But I understand if you don't want to include it.

Re: 8: The Dreamcast version of Final Egg 2 has a random piece of the tube segments at the origin of the level, while SADX does not. There's literally no point in it being there other than to take up space. It's not a big deal at all, but it may save slightly on file size.

**Comment by PiKeyAr** [comment] 2017-03-08 15:57
Thanks, I'll include your fixes in the next update and add you to the credits.

File size? Umm, I'm not sure that's how it works. The model of that object is most likely used in other tube segments, so if you remove that particular instance, you're going to save 100 bytes (from the deleted COL entry) at most. And that's _uncompiled_ code. And even if it was an entirely unused model, it wouldn't save more than a few kilobytes... 

Honestly I'd prefer to work on something more significant rather than bother with stuff you never even see ingame. Much like with SET files, there's no point in this kind of optimization - it brings zero performance improvement, and it's not worth saving a few kilobytes in a 1GB+ game.

**Comment by supercoolsonic** [comment] 2017-03-08 18:29
Maybe I have no idea of what I'm talking about with file size. I dunno. It was removed in SADX for some reason, but if not file size, then I have no idea why.

 But now I'm confused. I know the point of these mods is to change SADX levels and assets to the Dreamcast versions, and to be as accurate as possible when doing so. However, even the Dreamcast version isn't 100% perfect. Sonic Adventure is by no means a perfect game. It's very buggy, glitchy, and the presentation is very dated. ...But in my opinion, it's still really fun to play, and the control is smoother than anything we've gotten afterwards. If there's a way to even improve on the Dreamcast version, why not go for it when possible? I don't mean to halt work on the more basic things, like landtables or dynamic fog (not saying that fog is easy to make) to pursue massive feats like remodeling things to fix texture problems or fixing animations, but I report things on here that can be improved, whether or not it has to do specifically with the DC mods. I know you're not too interested in working with things that don't have to do with your mods, and that the purpose of the mods is to make SADX like the Dreamcast, but then you add neat little things like the coding in Emerald Coast 3 just to fix the ceiling of the secret fishing area. You don't have to do that, but you did.

 So I'm confused. Should I report things like the drowning animation and collision problems, in the hopes that they can be addressed some time in the future? Or refrain from doing so and only report problems that I know for sure are brought about by the DC mods alone? I thought for sure that the lighting feature in Lost World Act 2 would be something that could be considered for the DC mods in the future, seeing how the lighting on the player doesn't change on Dreamcast, but it does on SADX. And then it can cause a bug to occur.

I'm by no means trying to sound angry or appear hostile. If you got either of those from my statements above, then I apologize completely. Whatever you do with these mods is 100% up to you. I'm just uncertain as to what specifically you'd like to see in these reports, and if you're open to any suggestions or help. I'm not experienced in the coding part of this, but basic things like layouts are something I can ace at. If there's ever any problems with layouts, you can ask me about it.

Have a good day.


...Oh. One more thing I wanted to ask about. I recall asking you if there was any code-related changes in the SET files. The reason I asked that was because when working with the Angel Island area SETs for Sonic, Super Sonic, Knuckles, and Gamma, I accidentally overwrote the two Sonic files with Knuckles' file, after I had deleted the scene changer object in the Ice Cap room. (Let's just not talk about "optimization" here. It's not the point of this note) So I had to start over with their files, but not before trying to add back in the scene changer manually. What's weird, is that even though I gave the new scene changer the exact same attributes, rotation, position, and three variables as it had before it was accidentally erased, it would not load Ice Cap. It apparently was loading Ice Cap based on a slight X rotation originally, but would not do so this time. This convinced me that either the SET file was hardcoded to specifically load Ice Cap from that particular instance of the scene changer object, or the game checks the object list and looks for an object in the list at a certain position in the object list, and could no longer find the object that was now at the end of the list. Have you ever encountered anything like this?

**Comment by PiKeyAr** [comment] 2017-03-08 19:41
I absolutely agree that SA1 isn't perfect, and that it's still a fun game (if it wasn't fun for me, I probably wouldn't be working on this project). However, you're also correct that the main focus of this mod is to recreate SA1 graphics (and, to a lesser extent, sound) within the limits of SADX engine rather than a "fixed" version of SA1 on PC. And by that I mean I'm not interested in fixing design flaws with the original assets (unless fixing them is trivial, but in most cases it isn't), or changing physics/gameplay in any significant way. Same for non-serious collision issues, though, like I said, I'm not against other people adding minor collision fixes, provided that they are compatible with the DC mods.

As for what kind of reports I'm looking for, I'm generally interested in the following:

- Bugs with the DC mods that don't happen in unmodded SADX. E.g. walking into the hotel pool hurts the player.
- Potential accuracy improvements. If there's an object that clearly has a different-looking model (Speed Highway helicopter, cars, icicles etc.), is textured differently etc. - I totally want that. But not lighting (unless it's just ignore lighting on/off), since I can't change object lighting until SF94 is done with the API for me to do so. Transparency (layering) issues also go here, although I can't always fix them due to the limitations of SADX transparency sorting, and I usually decide whether it's worth trying to fix at all. For example, shield being invisible behind certain surfaces or transparent stuff being rendered above water isn't fixable in most cases. A lot of these issues may go away when a custom draw queue or proper transparency is implemented.
The ocean code I consider an accuracy improvement, since it's like that on the Dreamcast. I was able to implement it because I learned how to hack the Emerald Coast water to display SA1 textures just a bit earlier, which gave me an idea on how to fix the cave top.

Here are examples of things I'm not interested in:
- Design flaws (unless it's trivial to fix them). Example: visible seams between building parts in Station Square Casino area, or level geometry in the MR Ice Cap area.
- Control and gameplay-related issues, unless they're caused by my mods.
- Bugs that happen in all versions of the game (may or may not be picked up by the author of SADXFE).
- Bugs caused by errors in SADX code. I have a couple listed on this tracker because they're related to the accuracy of DC mods (e.g. Perfect Chaos effects), but even those would probably be better suited for SADXFE.
- Lighting-related feedback - especially character lighting, since that isn't touched by the DC mods in any way and can only be addressed on the PL mod's side of things.
- Things that are noticeable only outside normal circumstances. E.g. if you use a character that doesn't go to that level normally, or go to an area you can't go to during normal gameplay.
- Things that don't improve the experience in any meaningful way. E.g. cleaning up SET files or removing unused objects - unless doing that fixes some other issue.

No worries, and I hope I didn't come across as angry either. I'm certainly open for suggestions and help (within reasonable limits), and I really appreciate all the feedback you've had going on here. You've helped me fix quite a lot of things I would've overlooked otherwise!

As for the SET object issue, I haven't run into this myself, but I know SET objects often use fields like rotation and scale for other parameters. I suggest you just export the SET files as text files in DXEdit and compare the entries for both objects to see if there's any difference.

**Comment by supercoolsonic** [comment] 2017-03-08 21:19
...Oh. The issue with the ceiling in Emerald Coast wasn't a problem on the Dreamcast? I just went and checked, and sure enough. Huh. I swear that the last time I checked...

Well, don't I look like the biggest fool. That entire post and confusion was because I thought you added a nifty little fix to Sonic Adventure as a whole, instead of an accuracy improvement. I thought that would be fixed by porting the data over from the Dreamcast. So it was a problem with SADX itself, then.

Oh well. I'm glad we got this cleared up, though. ...But then you added the turbines back onto the Egg Carrier from SADX, and aligned the ruins properly in the Jungle area. (Sorry if it felt like I was pushing you for that. It just seemed like such an obvious problem with the original game that could easily be fixed)

Regardless, I'll heed to your wishes on what you'd like to receive with your reports. But just one more thing. And this will be the last time I bring this up if you don't want to hear about it. It's about the "optimization" I was talking about. What I mean by optimizing is making the game run as smoothly as it can while taking up the least amount of file space possible. And this is what I mean by SET optimizing. If not Knuckles' Lost World layout, how about Tails' file for Emerald Coast? It's used for the one cutscene, but contains all the objects for the entire level. If all objects except the ones on the final beach were deleted, it'd make the file size smaller without a visual change in-game. I know it's not that much smaller, but for those running this game on older computers and have to use the cliplevel function in the sonicDX file to get a smoother experience, this can reduce strain on the computer and save precious space. You know the game Super Mario Galaxy, right? Every time you enter a different mission in one of the levels, not all the objects across the entire level are loaded, much like most levels in this game. It's because it's optimized, so that it doesn't load things that it needs to, and helps keep a consistent framerate. Again, newer and more powerful computers usually don't have an issue running this game at 60fps, but for those that don't have the luxury of owning one, removing leftover objects in certain layouts can help even just a little bit.

But then there's just problems with the layout files in general. Two turrets in Knuckles' Sky Deck near where Sonic starts are facing the wrong way, and thus won't fire. Speaking of fire, the fire arrow shooters along the boulder path in Sonic's Lost World Act 2 could fire...fire arrows, which would explain why the boulder catches on fire to begin with. What about in Tails' Speed Highway, to the left of the helicopter landing pad, that have arrow signs in the little nook that have arrows placed that clip into other arrow signs? There's a swinging spikeball near the bottom of the shaft that Gamma goes down after the cargo section that has its balls spinning outside the level model, making it a complete non-threat. The adventure fields aren't excluded from this. The archeologist that walks near Big's house where I reported the texture issue on the path will walk right through a fallen tree. There's the palm tree that's placed below the Angel Island area for some reason, and there's a Final Egg door placed above the door on the lower floor of the Final Egg room in Mystic Ruins. The list goes on and on.
Another kind of mistake is duplicate objects, or double rings. Did you know that in Tails' Speed Highway file most of his street light objects in the first half of the stage have two placed in the exact same spot? And there's over 40 of them that have an extra object there that doesn't need to be there. Speed Highway Act 3 for both Sonic and Knuckles have many objects like this, but most of them aren't visible in-game. But there are a few that are. In Lost World Act 2, again for both, one of the wall panels has a duplicate inside it, and when it lights up, it looks different than the others because its light is "brighter". It's loading two at once, and it sticks out. The final spring in that long spring path in Windy Valley Act 3 has two springs placed in the same spot, and you can hear the difference if you listen close enough when you smack into it. And then there's the Tornado segment. In Act 2 of Windy Valley, that bridge that's in the tornado is actually two bridges. Two. Why? There doesn't need to be two. There's no need for the game to run the bridge code twice, render two bridges, and calculate collision with the bridge twice. This is the optimization that I mean. I don't mean that you have to fix these things, but I've fixed most of them. Any I find, I try to remedy, and while each individual edit doesn't improve much or maybe anything at all, then I have to wonder why professional game companies usually pay attention to this and have their games this way.

Again, not trying to sound mad, and I'm not trying to push you to do anything. It's just an attempt to help you understand where I'm coming from.

 And so I have another question. If I were to apply these fixes to your own SET files that come with the mods, and I get your approval for each, would you use them? I wouldn't do anything drastic like I mentioned before, with deleting most of the layout for those two files. But what about deleting duplicate objects, fixing floating grass or similar things, or maybe adding something. Are you aware of the CARRIER objects in Sky Deck? I think you improved the draw distance for them, right? There's one for each act, and they're invisible objects that generate a lot of models in specific locations in the level to further match the levels up with actual areas on the Egg Carrier. ...One of them isn't used. CARRIER3, used in the Autodemo, generates models that match up with the level model and make it look even better. You can see parts of it in some of the screenshots I posted. In fact, here's an example:
![a new tower](https://cloud.githubusercontent.com/assets/26051785/23724039/f7efeff8-0410-11e7-95d4-d381ba732564.png)
It's that building that you can now see clearly at the end of Act 2! This isn't normally here. And it it looks great.

 I'm not saying to use every unused object, but something like this would be harmless, right? So, could I help improve the layouts of the SET files from your mods? I would submit a detailed list of every change I make and let you see it before giving you the edited files.

**Comment by PiKeyAr** [comment] 2017-03-09 07:40
> But then you added the turbines back onto the Egg Carrier from SADX, and aligned the ruins properly in the Jungle area.
I restored the turbines because it was easy to take advantage of their SADX counterparts, so I thought - why not? The alignment issue was caused by my fix for #24, the replacement mesh just needed to be aligned a little.
>  If not Knuckles' Lost World layout, how about Tails' file for Emerald Coast? It's used for the one cutscene, but contains all the objects for the entire level. If all objects except the ones on the final beach were deleted, it'd make the file size smaller without a visual change in-game.
I'm still convinced this kind of optimization is useless and even undesirable, because:
1. The SET objects are programmed to clip at a certain distance, which means only the objects around that area in the cutscene are loaded at all.
2. I don't understand why you insist on saving space by trimming a 30KB SET file. There are other ways to save space and improve loading speeds a lot more, for example converting all the png textures used in the mods to dds.
3. If you remove Tails' layout for the stage, I'm 99% sure someone else will complain because they use the character select mod to get Tails into that stage or whatever. I don't officially support that either, but I'd like to avoid more complaints, especially in this case where it brings literally zero benefit. "If it isn't broken, don't fix it".
4. The older computers are going to have a lot more trouble handling the PL mod and increased level draw distance rather than any of the SET objects.

> But then there's just problems with the layout files in general.
Most of these are good to have fixed, yes. I wouldn't add fire arrows though since they aren't there in the original.

> Another kind of mistake is duplicate objects, or double rings.
These are also good, provided that the duplicate objects weren't put there on purpose to fix some issue, which I wouldn't be surprised with in this game.

> If I were to apply these fixes to your own SET files that come with the mods, and I get your approval for each, would you use them?
I think the best way around it would be to make a mod called "supercoolsonic's fixed SET layouts for DC mods" or something along those lines, and have a link to them in the install guide. As for including them in the main package - after some testing, maybe.

>About the master emerald shards, would it be possible to make them look more like they did on the Dreamcast?
Possible (unless it's lighting-related), I may look into it soon.

>These columns in Casinopolis have no collision.
That might be the result of your optimization. I can't reproduce this with my SET files (those columns have SET collision spheres and cylinders inside them).

>I've closely looked at the missile object in Tails' Speed Highway, and it appears that more of it is visible in the Dreamcast version compared to SADX, even though the missile is in the exact same spot in both versions, same variables and everything.
It could be that the missile object has ordering issues, which cause it to render behind the landtable piece. May be fixable by reordering the model, or just moving it a little.

**Comment by PiKeyAr** [comment] 2017-03-09 12:45
Actually, about that Lost Water character lighting thing. I was able to fix it independently of the lighting mod (the dynamic fog function for that area specifically disables character lighting). Unfortunately this doesn't help the glitch that occurs after exiting from the stage in Trial mode while in the mirror room.

**Comment by supercoolsonic** [comment] 2017-03-09 14:38
...Oh, I know what happened with the columns. Never mind about them. I'm learning more about the loading methods of the game, here. So, if the objects don't clip, they aren't loaded? But what about the Oribnaut that was having problems spawning in Sky Deck 3?

There are actually fire arrow shooters already in place at the boulder sequence. They just don't fire. They're decorative, but if they are made to fire, it would make sense as to why the boulder catches fire, instead of it just....being on fire for no reason.

Also, Tails is immediately booted out of Act 2 in Emerald Coast, so that layout can never be used, anyway.

The only duplicate objects I don't touch are collision. I believe those have a reason for having multiple copies in one spot. Others ones, nope. Mistakes. I've tested the levels more times than I could ever hope to fathom, even without these duplicates, and everything works fine.

I'll shut up about "optimizing", because it's not a service that we agree on, and you'd probably never accept those kinds of edits anyway. I want to look further into how SADX loads things, too. Then I'll know what I'm talking about. Unless you want to continue this conversation, this will be my last post in this issue. I'll make a new one when I find more problems.

**Comment by PiKeyAr** [comment] 2017-03-09 15:08
> But what about the Oribnaut that was having problems spawning in Sky Deck 3?
There's a difference between SET objects and landtable objects. SET objects have an arbitrary clipping distance specified in their code, while landtable objects have that thing called "bounds" in the landtable's COL list. The orbinaut fix had to do with the bounds for the level piece it was supposed to be on, the bounds had to be adjusted so that the level piece wouldn't disappear at the start.

**Closed by PiKeyAr** 2017-03-09 15:08 UTC

**Comment by PiKeyAr** [comment] 2017-03-09 15:18
Also, I'm not really against removing duplicate objects if it fixes issues (the Lost World panel one is a really nice find). There are also a few things like item capsule rotation in some levels I still want to tweak.
As for the other optimizations, e.g. removing unused stuff: unless it fixes problems with the game I'd rather leave it as is.
