### ISSUE TITLE
Twinkle par Inaccuracy 

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#87] opened 2017-03-15 06:47 UTC
there's only one slider in the PC version
![capture](https://cloud.githubusercontent.com/assets/15071652/23936640/ae850880-0929-11e7-8184-4be66db72aa4.PNG)

There's two in the DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23936651/c17ce372-0929-11e7-8bdc-f19b1f87820b.PNG)

**Comment by Zetchzie** [comment] 2017-03-15 06:50
The water enemies have a green tint in PC
![capture](https://cloud.githubusercontent.com/assets/15071652/23936724/0b36a62e-092a-11e7-8eb9-ab3e04c425b3.PNG)

They should be blue as in DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23936738/1bedc70e-092a-11e7-9afc-f02bffc0f1d8.PNG)

**Comment by Zetchzie** [comment] 2017-03-15 06:53
Plants use different models PC
![capture](https://cloud.githubusercontent.com/assets/15071652/23936812/83fca608-092a-11e7-92c0-1513f44f0aa7.PNG)

DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23936827/8fa5b0a8-092a-11e7-9c0d-b0f01ed07d11.PNG)

**Comment by supercoolsonic** [comment] 2017-03-15 07:16
The slider (Sweep) is caused by a bounds issue. Odd. It spawns normally in the Dreamcast version. I thought it always had trouble spawning only in SADX.

Buyon is probably a palette thing.

Plants model is already known and is not currently being used due to alpha issues.

**Comment by PiKeyAr** [comment] 2017-03-15 12:12
>there's only one slider in the PC version

I don't think it's a bounds issue, but even if it is, I don't know how to fix it. There was a similar issue in SADX with the Leon badnik, which was fixed in the Mod Loader's code. Maybe the author of SADXFE can figure it out? I've split it into a separate issue to keep track of it.

>The water enemies have a green tint in PC

This is a material color issue. I couldn't find some of the models involved, but there will be a universal material color fix soon.

>Plants use different models PC

This is a known issue. I left them disabled on purpose because of unfixable transparency problems.

**Closed by PiKeyAr** 2017-03-15 12:12 UTC
