### ISSUE TITLE
Too dark lava in Lava Mountain

### ISSUE THREAD

**Issue by Zarazek2000** [PiKeyAr/sadx_dreamcast#248] opened 2022-04-30 07:25 UTC
Hey there! Back in the day the lava in the Lava Mountain was pretty much identical to this in the Dreamcast version of Sonic Adventure, but for some reason in the newest version of Dreamcast Conversion lava is really, really dark. I don't know if this is just a bug in the newest version or whatever, but I wanted to mention this, 'cause it looks really weird and it is not as it supposed to be.
![htdxf](https://user-images.githubusercontent.com/102874745/166096242-148ab434-32a1-45e0-8a49-5f17fc67484b.png)
.

**Comment by PiKeyAr** [comment] 2022-04-30 08:35
This is caused by a change I made to the Lantern Engine mod that alters parsing of material colors to be more like the vanilla version of SADXPC. There will be a Mod Loader update in the near future that fixes issues like this on all models in the game.

**Comment by Zarazek2000** [comment] 2022-05-01 06:16
> This is caused by a change I made to the Lantern Engine mod that alters parsing of material colors to be more like the vanilla version of SADXPC. There will be a Mod Loader update in the near future that fixes issues like this on all models in the game.

Oh okay, thanks for the answer! Just one more question, since it is an issue with the Lantern Engine mod and not with the Dreamcast Conversion mod, should I close this issue or should I leave it until it fixed?

**Comment by PiKeyAr** [comment] 2022-05-01 06:48
Let's keep it open until it's resolved.

**Comment by PiKeyAr** [comment] 2022-05-05 06:21
Should be fixed with the latest Mod Loader update.

**Closed by PiKeyAr** 2022-05-05 06:21 UTC
