### ISSUE TITLE
The game crashes when entering to Angel Island

### ISSUE THREAD

**Issue by kawaiikaorichan** [PiKeyAr/sadx_dreamcast#218] opened 2019-12-07 01:15 UTC
When you try to access the Angel Island using any character, the game will crash about the begining of the ice cave. The game stops crashing when Mystic Ruins are disabled from the mod. This happens whenever a mod that modifies textures is enabled or disabled. That didn't happen before.
![Mod loader](https://user-images.githubusercontent.com/58614003/70366417-c6d30f00-185c-11ea-8cff-368a60ce331a.png)

**Comment by PiKeyAr** [comment] 2019-12-07 03:17
Based on the information you provided, I could not reproduce this.
![image](https://user-images.githubusercontent.com/23312549/70368206-53c4a980-18eb-11ea-97bb-a7f44bdbd8fd.png)
![image](https://user-images.githubusercontent.com/23312549/70368209-5cb57b00-18eb-11ea-96b2-aaf27b16543e.png)
Make sure the mod has been updated correctly (verify integrity to see if there are any missing files).

**Comment by kawaiikaorichan** [comment] 2019-12-07 03:27
I think it maybe was a glitch caused by the existence of a save file in which, when starting Super Sonic's story, you play an Action Stage (I played Windy Valley), then you quit the game, and when selecting again that story, you can't access anymore to that section. I'm saying this because I tried to cause it again (I was going to upload a video to show you what happened) after I could complete the story disabling Mystic Ruins, and now it doesn't happens.

**Comment by PiKeyAr** [comment] 2019-12-07 03:47
That doesn't sound like it could be causing a crash specifically with DC Conversion, but if you manage to get a savefile where it's consistently reproducible I'd like to have a look.

**Comment by PiKeyAr** [comment] 2019-12-22 06:50
I had some time to test this, so I started Super Sonic's story, beat Windy Valley, quit the game, loaded it again and I was able to access Angel Island just fine. It may have been caused by something else but I was unable to get the game to crash on Angel Island even after I enabled your mod. Closing this for now.

**Closed by PiKeyAr** 2019-12-22 06:50 UTC
