### ISSUE TITLE
Egg Carrier Chao Egg Issue

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#91] opened 2017-03-16 08:54 UTC
![capture](https://cloud.githubusercontent.com/assets/15071652/23988390/70308f9c-0a04-11e7-9ca9-9940b703acb8.PNG)
The egg you find in the egg carrier cell turns black once in the chao garden 

Its should look like this
![capture2](https://cloud.githubusercontent.com/assets/15071652/23988679/9ba5275e-0a05-11e7-837d-979928fdd654.PNG)

**Comment by PiKeyAr** [comment] 2017-03-16 08:57
Does it happen without the DC_ChaoGardens mod?

**Comment by Zetchzie** [comment] 2017-03-16 08:58
yes

**Comment by PiKeyAr** [comment] 2017-03-16 10:10
Looks like it happens even with the Mod Loader uninstalled, so it isn't caused by the mods. Could be a texlist issue. Apparently it happens on the Gamecube version too, perhaps they couldn't fix it because it displays black textures even onboard the Egg Carrier.

Chao eggs are chunk objects, which are seriously under-researched, so I wouldn't expect a fix for this to come anytime soon. I've added it to the list of known issues.

**Comment by PiKeyAr** [comment] 2017-03-16 11:17
Okay, I spent some time looking at things and found out it isn't really a bug, but more like a design inconsistency caused by the change in the Chao system between SA1 and SADX. 

The SADX egg is actually a Monotone Black egg, which displays as it should in the garden and can be purchased on the Black Market. SA1 only has this unique egg, which is textured differently. So the reason it turns black in SADX is that the egg model changes to the Monotone Black egg model as soon as you bring it to the garden. There are 2 ways to fix this:

1. Easy - change the texture on the Egg Carrier egg to match the Monotone Black egg (which is what it's like on the Gamecube).
2. Difficult - hack the Monotone Black egg to make it look like the unique SA1 egg.

I'd like to go with (2) in the long term, but it's not gonna be easy to change, even though I've already found the function that renders the Monotone Black egg. Like I said above, Chao eggs use chunk models, which are difficult to hack. Secondly, the model used for the Monotone Black egg is the same model used for all Chao eggs, it actually has the texture of a normal egg, but it's painted over with material effects. Finally, the PVM used by those eggs (AL_BODY) has textures that use external palettes, so just adding a new texture wouldn't be very easy.

**Comment by PiKeyAr** [comment] 2017-03-16 14:54
Well, holy crap.
![sonic_2017_03_16_23_52_56_627](https://cloud.githubusercontent.com/assets/23312549/24002316/c55c8a3a-0aa3-11e7-9116-785f2cf459db.png)
I had no idea this would be possible, but I think I'll be able to implement this properly.

Obvious side effect: all Monotone Black eggs will be like this.

**Comment by Zetchzie** [comment] 2017-03-16 22:01
I wonder why the Roach Chao was removed in SADX

**Comment by LimitCrown** [comment] 2017-03-20 07:36
A notable thing about the black egg in the Dreamcast version of Sonic Adventure is that a Two-Tone Grey Chao hatches from it instead of a Monotone Black Chao. Also, in Sonic Adventure DX and Sonic Adventure 2 Battle, there are two-tone egg colors that ended up being unused in the games.

As an alternative, if you do make it so that a two-tone grey Chao with the correct genes is brought into the garden, I would suggest altering that two-tone egg color to resemble the Dreamcast Sonic Adventure's black egg instead. It doesn't matter too much, though.

**Comment by Zetchzie** [comment] 2017-03-20 08:03
the egg carrier chao is a roach chao

**Comment by LimitCrown** [comment] 2017-03-20 08:21
I'm fairly sure that the Egg Carrier Chao is only a Two-Tone Grey Chao.

**Comment by Zetchzie** [comment] 2017-03-20 08:24
it is but it was only obtainable in SA1 at the time afaik

**Comment by LimitCrown** [comment] 2017-03-20 08:27
Yeah. The Two-Tone Black Chao, which is the same color as Chacron from SA1, was obtainable only from SA2's Black Barket.

**Comment by Zetchzie** [comment] 2017-03-20 08:28
yea you needed internet to get him

**Comment by PiKeyAr** [comment] 2017-03-20 20:05
Thanks to MainMemory I was able to find the code that sets the egg type for it, so making it a two-tone gray egg is easy now. The only issue with this replacement is consistency with the other two-tone egg colors. The texture is distictly black, and looks darker than the black two-tone egg, for example. One solution to this is to make custom textures for two-tone eggs. I'll see what I can do, but if anyone feels like doing it, both normal and black textures are in textures/AL_BODY folder of the DC_ChaoGardens mod.

**Comment by PiKeyAr** [comment] 2017-03-20 20:22
So far without extra textures I've been able to do the following:
![eggs](https://cloud.githubusercontent.com/assets/23312549/24119769/a8ab266c-0df5-11e7-83ac-fc759bb965bd.png)
From top to bottom: grey two-tone, black two-tone, grey shiny two-tone, black shiny two-tone.

**Comment by Zetchzie** [comment] 2017-03-21 02:54
I dont think the game offers any other two tone eggs besides normal and that one. the rest are pretty solid

**Comment by PiKeyAr** [comment] 2017-03-21 03:29
I think the only issue for now is the shiny two-tone black and gray eggs looking very similar, but they look kinda similar in the unmodded game too so I guess I'll leave it like this for now. If I ever make/find custom textures for all two-tone eggs, I'll update it.

**Closed by PiKeyAr** 2017-03-21 03:29 UTC

**Comment by LimitCrown** [comment] 2017-03-23 20:07
Earlier, I had stated that the Black Chao was a Two-Tone Grey Chao, but I was incorrect. From the pictures that Jmtshaw showed, the Chao that hatches from the egg looks like a Two-Tone Black Chao and is the same as Chacron. I previously refered to information from the website, so I apologize for the mistake.
